defaults:
  - _self_
  - logging/hydra_config
  - logging: other_loggers
  - model: hf_config
  - data: CeLLaTe_V2
  


task_type: "ner"
seed: 3407
num_epochs: 20
batch_size: 16
warmup_ratio: 0.1
optimizer: "AdamW"
eval_batch_size: 16
lr: 2e-5 #options [1e-4, 5e-5]

use_wandb: true
training_strategy: reinit_only #type of training strategy: Options[base, reinit_only, reinit_llrd, partial_freeze, peft]

#reinit strategy parameters
weight_decay: 0.01
reinit_k_layers: 2
reinit_classifier: false
# reinit_pooler: false
llrd: 0.9 #options [0.9, 0.95]

