defaults:
  - _self_
  - logging/hydra_config
  - logging: other_loggers
  - model: hf_config
  - data: phee_ae


task_type: "ner"
seed: 3407
num_epochs: 10
batch_size: 16
warmup_ratio: 0.1
optimizer: "AdamW"
eval_batch_size: 16
lr: 2e-5


use_wandb: true