defaults:
  - _self_
  - logging/hydra_config
  - logging: other_loggers

inference_dataset_path: OTAR3088/CeLLaTe-V2-all #dataset path: Local or HF
hf_model_path: null #dataset model path
wandb_artifact_dir: ebi_literature/otar-3088/hf-CeLLaTe_V2-reinit_only-LR_2e-05-4K-Layers-no_reinit_classifier-Training:v0 #TODO - These naming methods haven't been fixed yet

fetch_from_wandb: true #whether to load model from wandb
fetch_from_hf: false #whether to load model from hf
output_dir: null #wandb logging dir, hf reulst output dir
label_col: tags #name of column containing label list
text_col: tokens #name of column containing tokens list


seed: 3407 
data_seed: $seed
batch_size: 16

use_wandb: true #wheter to log and use wandb
