# config/logging/other-loggers.yaml
wandb:
  run:
    project: otar-3088
    dir: logs/${model.name}/${data.name}_${data.version_name}
    entity: ebi_literature                    
    tags: ["${model.name}", "${data.name}", "ner", "hydra"]
    
  registry:
    registry_name: CeLLaTe-Entities
    collection_name: CeLLaTe-Models


loguru:
  level: DEBUG
  #rotation: 1 week
  #retention: 2 months
  log_dir: logs/${model.name}/${training_strategy}/${data.name}_${data.version_name}
  log_filename: ${model.name}_${data.name}_model.log