# TESTING - Reviewing hyperparameter tuning with hf trainer.hyperparameter_search
# With this, reusing old data from PHEE
name: hf_finetuning
version_name: "phee_ae_V1"
data_folder: "Datasets/${.version_name}" #used for model training only

# No preprocessing needed

#for hf
file_format: "conll"
source_type: "local"
train_file: "${.data_folder}/PHEE_train_v1.${.file_format}"
test_file: "${.data_folder}/PHEE_test_v1.${.file_format}"
val_file: "${.data_folder}/PHEE_eval_v1.${.file_format}" 

# Options to add hyperparameter finetuning
fine_tune: true
tune_trials: 3 # This could default to ~ 10 once working