

# Model & Tokenizer
model_name_or_path: Mardiyyah/cellate2.0-tapt_base-LR_5e-05

# Training hyperparameters
args:
  learning_rate: ${lr}
  per_device_train_batch_size: ${batch_size}
  per_device_eval_batch_size: ${eval_batch_size}
  num_train_epochs: ${num_epochs}
  weight_decay: ${weight_decay}
  warmup_ratio: ${warmup_ratio}
  dataloader_num_workers: 0
  save_steps: 100
  eval_steps: 100
  #warmup_steps: 500
  lr_scheduler_type: linear
  overwrite_output_dir: true

  # Logging and evaluation
  logging_steps: 100
  logging_strategy: steps
  eval_strategy: steps
  save_strategy: steps
  save_total_limit: null 
  load_best_model_at_end: true
  metric_for_best_model: eval_f1
  greater_is_better: true
  group_by_length: true
  do_train: true
  #gradient_accumulation_steps: 2

  # Optional params 
  fp16: true #mixed precision for faster training on GPU 
  seed: ${seed}
  data_seed: ${seed}

use_data_aug: false
data_aug_method: gazetteer
max_ent_per_type: 5000
aug_prob: 0.4

use_weighted_trainer: false

ner_tag_list: [B-CellLine, I-CellLine, B-CellType, I-CellType, B-Tissue, I-Tissue, O]
label_names: [CellLine, CellType, Tissue]
