# config/logging/other-loggers.yaml
wandb:
  run:
    project: otar-3088    
    entity:  ebi_literature     
    job_type: training                

    
  registry:
    registry_name: CeLLaTe-Entities
    collection_name: CeLLaTe-Models